### ISSUE TITLE
A working example

### ISSUE THREAD

**Issue by alouane** [Defina-se/angular-clappr#1]
Hi!
Can you provide a demo code on how to use this directive?
Cheers

**Comment by washingtonsoares** [comment]
Hi @alouane !

Thank you for your interest. 
It is very simple to integrate this directive in your code.
Basically you need to call through directive their tags: 

`<clappr src="src"></clappr>`

Remembering that "src" attribute receives a $scope object that contains video URL.

Sorry for this directive still does not have documentation, but is already in my plans to do this, and other improvements. 
Feel free to do some fork or PR, all help will be appreciated! :)

Any questions do not hesitate to contact.
[]`s

**Comment by alouane** [comment]
Ok, Thank you sir!
Cheers
